sudo: false
language: python
python: "3.4"
cache:
    directories:
        - mysql

env:
    matrix:
        - TOX_ENV=py26
        - TOX_ENV=py27
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=pypy
        - TOX_ENV=pypy3

matrix:
    include:
        - addons:
             mariadb: 5.5
          env: TOX_ENV=py27
        - addons:
             mariadb: 10.0
          env: TOX_ENV=py33
        - addons:
             mariadb: 10.1
          env: TOX_ENV=py34
        - env:
             - TOX_ENV=py34
             - DB=5.6.26
          addons:
              apt:
                 package:
                     - libaio1
#        - env:
#             - TOX_ENV=py34
#             - DB=5.7.8-rc

install:
    - pip install -U tox

before_script:
    - if [ ! -z "${DB}" ]; then
          F=mysql-${DB}-linux-glibc2.5-x86_64;
          wget http://cdn.mysql.com/Downloads/MySQL-${DB%.*}/${F}.tar.gz --directory-prefix=${HOME}/mysql/ -nc ;
          P=${HOME}/mysql/${F} ;
          [ -d  ${P} ] || tar -zxf ${P}.tar.gz --directory=${HOME}/mysql ;
          ${P}/scripts/mysql_install_db --basedir=${P} --datadir=${HOME}/db-"${DB}" ;
          ${P}/bin/mysqld_safe --ledir=/ --mysqld=${P}/bin/mysqld  --datadir= ${HOME}/db-${DB} --socket=/tmp/mysql.sock --port 3307 --innodb-buffer-pool-size=200M  --lc-messages-dir=${P}/share --plugin-dir=${P}/lib/plugin/ &
          mysql -S /tmp/mysql.sock "create user ${USER}@localhost; create user ${USER}@'%'; grant all on *.* to  ${USER}@localhost WITH GRANT OPTION;grant all on *.* to  ${USER}@'%' WITH GRANT OPTION;";
          sed -e 's/3306/3307/' -e 's:/var/run/mysql/mysql.sock:/tmp/mysql.sock:' .travis.databases.json > pymysql/tests/databases.json;
      else
          cp .travis.databases.json pymysql/tests/databases.json;
      fi
    - "mysql -e 'create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'select VERSION();'"

script: tox -e $TOX_ENV
